name: work_flow
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  get_it: ^7.7.0

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  image_picker: ^1.2.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^8.1.4
  injectable_generator: ^2.6.1
  build_runner: ^2.4.12

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/core/database/migrations/
    - lib/assets/images/
    - lib/assets/icons/